CREATE TABLE roster_policies (
 ward_id VARCHAR(36) PRIMARY KEY,
 policy JSON NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (ward_id) REFERENCES wards(id)
);